### ISSUE TITLE
OpenLogic CentOS7 updates repo currently not available

### ISSUE THREAD

**Issue by tbugfinder** [openlogic/AzureBuildCentOS#108] opened 2021-01-26 08:28 UTC
https://github.com/openlogic/AzureBuildCentOS/blob/49f0e78b3f2db017295966c7fd041257afe2e12a/config/azure/CentOS-Base-7.repo#L25

Hi,

today I cannot deploy new VMs which depend on the updates repo.
It looks like the updates folder is missing.
Is a maintainer of the repo available here or where should I go to?

```
# yum repolist
Loaded plugins: fastestmirror, langpacks, priorities, product-id, search-disabled-repos, subscription-manager, versionlock

This system is not registered with an entitlement server. You can use subscription-manager to register.

Loading mirror speeds from cached hostfile
 * base: mirror.ash.fastserv.com
 * epel: mirror.umd.edu
 * extras: mirror.datto.com
 * updates: atl.mirrors.clouvider.net
http://olcentgbl.trafficmanager.net/centos/7/updates/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

http://olcentgbl.trafficmanager.net/centos/7/updates/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
repo id                                                                                   repo name                                                                                                     status
base-openlogic/7/x86_64                                                                   CentOS-7 - Base (OpenLogic)                                                                                   10,072
extras-openlogic/7/x86_64                                                                 CentOS-7 - Extras (OpenLogic)                                                                                    448
updates-openlogic/7/x86_64                                                                CentOS-7 - Updates (OpenLogic)                                                                                     0
base/7/x86_64                                                                             CentOS-7 - Base                                                                                               10,072
epel/x86_64                                                                               Extra Packages for Enterprise Linux 7 - x86_64                                                                13,512
extras/7/x86_64                                                                           CentOS-7 - Extras                                                                                                448
openlogic/7/x86_64                                                                        CentOS-7 - OpenLogic packages for x86_64                                                                          22
packages-microsoft-com-prod                                                               packages-microsoft-com-prod                                                                                      759
puppet5/x86_64                                                                            Puppet 5 Repository el 7 - x86_64                                                                                270
updates/7/x86_64                                                                          CentOS-7 - Updates                                                                                             1,207
repolist: 36,810

```

Thanks & Best

**Comment by N3WWN** [comment] 2021-01-26 15:44
Thanks for pointing this out!  

I'm testing a fix right now and hope to have the `7/updates` repo back online ASAP.

**Comment by N3WWN** [comment] 2021-01-26 17:10
This was only an issue on 3 of our client repos.  Based on geographic distribution and load balancing, most users would not have seen any degradation of service, but those who did, would see it consistently.

Our monitoring shows that the issue is now completely resolved with the fix I pushed earlier. 

Please let me know if you continue to experience any issues.

Thanks!

**Comment by tbugfinder** [comment] 2021-01-26 17:57
Thank you so much. It's fixed also for us.

**Comment by N3WWN** [comment] 2021-01-26 19:28
Closed due to be resolved.

**Closed as completed** 2021-01-26 19:28 UTC
Labels: bug
